default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: ozzy@1414

development:
  <<: *default
  database: elevator_backend_development

test:
  <<: *default
  database: elevator_backend_test

production:
  <<: *default
  database: elevator_backend_production
  username: elevator_backend
  password: <%= ENV['ELEVADOR_DATABASE_PASSWORD'] %>
